language: node_js
node_js:
- 10
branches:
  only:
  - master
addons:
  ssh_known_hosts: vdorchan.com
script:
- rsync -avu --progress --delete . root@vdorchan.com:/srv/www/test-travis/
before_install:
- openssl aes-256-cbc -K $encrypted_c6db3232b98f_key -iv $encrypted_c6db3232b98f_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
after_success: 
- ssh root@vdorchan.com './deploy_shell_script'